### ISSUE TITLE
Script file todo

### ISSUE THREAD

**Issue by brakedust** [lcosmin/cmd2#1]
For running script files on the local host, the following change is needed:

Change line 1191 from
`if isinstance(fname, file):`

to 
`if os.path.isfile(fname):`

**Comment by lcosmin** [comment]
It seems the original author of this module has continued the development at https://bitbucket.org/catherinedevlin/cmd2 , https://pypi.python.org/pypi/cmd2 . 

Better report this issue there, if it still applies, as I don't maintain this fork anymore.

**Comment by brakedust** [comment]
Thanks!  I have now done that.
